<script>
  import { position } from "../position.js";
</script>

<img
  src="https://avatar.maplestory.nexon.com/Character/JOLAEBGKCPHBBBOGNCMPJOEPMNOAKPKLLLLKFLOGOKNMKAHIAADDHNJIALJHKFLPDDOHDBKNDNGGHKENHCJLEDILPNDKNGLAOFCOJJBBKKFOMGJKDJBFOAIENNEJGDLBPFKEENCOILGKEGPFAPBBEKJIPMDJMCGLFLIANMJDGPOGPGFIMMCEFAIMPEJMMOGGCOBOMGPDJMCMKMJKAHBALBPDKLBBHEBJHJKFBGMOOOEBODDBILLMPIIMPAJEIEPM.png"
  alt="캐릭터 이미지"
  class="character"
/>

<style>
  .character {
    position: absolute;
  }
</style>
